### PR TITLE
Use inline styles for general purpose layout

### PR DESCRIPTION
**Pull request by einarlove**
I thought the CSS from `toasted-notes/src/styles.css` was optional, but I quickly found out that was not the case unless you add global Toast_* specific styles.

This pull request tried to remedy this by adding inline styles for the positioning of the notifications and leaving the decision on styling the notifications up to the developer.

I did not find a Prettier or ESLint config so not sure if the formatting is consistent with yours, and not proficient in TypeScript so not sure if I did it correctly.

### CODE REVIEW

**Comment by bmcmahen** [comment]
Thanks @einarlove! I think this is probably a good idea and it lowers the barrier to entry for using this library. On first glance, everything looks good (I'm no Typescript expert either), but I'll give it a more serious look over the coming days and get this merged.

**Comment by bmcmahen** [comment]
You rock! Thanks.

**Comment by einarlove** [comment]
Something to note in the readme, now that flex styles are applied inline instead via a .css file, most people have to way of auto-prefixing the styles. Meaning this library does not support Internet Explorer 10 and iOS < 2015 by default.

A remedy is to style the default layout themselves with the classnames, use a prefixing utility when we inline the styles, or use an alterntive layout method than flex like display inline-block with ltr/rlt.

**Comment by bmcmahen** [comment]
It's a good point. I'm personally not too concerned about supporting those browsers and, like you said, support is there via classnames and autoprefixing if necessary.

**Pull request merged**
